/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p device_proxy -c DeviceProxy -i dbus_types.h org.PulseAudio.Core1.Device.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "device_proxy.h"

/*
 * Implementation of interface class DeviceProxy
 */

DeviceProxy::DeviceProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DeviceProxy::~DeviceProxy()
{
}

